### ISSUE TITLE
Value "5" for the Counter in the SSR output

### ISSUE THREAD

**Issue by koudonojinchuu** [svelte-view-engine/example#1]
Hi, first of all, thank you a lot for this admirable work. It integrates extremely well with Node (Express, etc).

My question is about this example,
when I run it and inspect its SSR output (the `html` variable), it says it is `"5"`, and I can check on the browser that it starts counting at 5.
But when I check the code, I see that:

```javascript
const Counter = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
  let { count } = $$props;

  onMount(async function () {
    while (true) {
      count++;
      await sleep(1000);
    }
  });

  if ($$props.count === void 0 && $$bindings.count && count !== void 0) $$bindings.count(count);
  return `${escape(count)}`;
});
```

And then I check how the `$$props` is fed, and I see that:

```javascript
const Home = create_ssr_component(($$result, $$props, $$bindings, $$slots) => {
  let { initialCount } = payload$1.get();
  return `${validate_component(Counter, "Counter").$$render($$result, { count: initialCount }, {}, {})}`;
});
```

But then, `payload$1` is just `payload`, and its value is never set (no call to `set()` in the SSR code):

```javascript
let g = typeof window !== "undefined" ? window : commonjsGlobal;

var payload = {
  set(value) {
    g.props = value;
  },

  get() {
    return g.props;
  },
};

var payload$1 = payload;
```

So, how comes it gives `"5"`? Is it a random value from the uninitialized memory?
But when I ask `g.props` (by instrumenting the code of `src/payload.js` in the `svelte-view-engine` module) it gives me `undefined`, so surely it cannot just get its `initialCount` value, right?

I do not have extensive experience in JS, so maybe my whole question is moot... just let me know without hesitation ^^;

**Comment by cbenz** [comment]
https://github.com/svelte-view-engine/example/blob/166a8a6dcb63fc1969332034953291989bccb8bb/src/main.js#L35

**Comment by koudonojinchuu** [comment]
Wow! Many thanks :)
